#!/usr/bin/python3
import os
import sys
from subprocess import (
    call,
)

sys.path.append('hooks')
sys.path.append('lib')

from charmhelpers.core.hookenv import (
    action_get,
    status_set,
)

from charms.layer.lxd_proxy import (
    save_ip_tables,
)


if __name__ == "__main__":

    host_port = {'host': action_get('host'),
                 'port': str(action_get('port'))}

    status_set('maintenance',
               "Forwarding port: {port} to {host}:{port}".format(**host_port))

    save_ip_tables(host_port['host'], host_port['port'])

    status_set('active', "Forwarding complete")
