#!/usr/bin/python3
import sys

sys.path.append('hooks')
sys.path.append('lib')

from charmhelpers.core.hookenv import (
    action_get,
    status_set,
)

from charms.layer.lxd_proxy import (
    save_ip_tables,
)


if __name__ == "__main__":

    host_port = {'host': action_get('host'),
                 'source_port': str(action_get('source-port')),
                 'dest_port': str(action_get('dest-port'))}

    status_set('maintenance',
               "Forwarding port: {source_port} to {host}:{dest_port}".format(**host_port))

    save_ip_tables(host_port['host'], source_port=host_port['source_port'],
                   dest_port=host_port['dest_port'])

    status_set('active',
               ("Forwarding complete {source_port} -> "
                "{host}:{dest_port}").format(**host_port))
